export const cavEspecialCanto = {
    title: 'CANTO DO CAVALEIRO ESPECIAL',
    text: ['SALVE DEUS!\n', 'OH JESUS! ESTA É A HORA PRECISA DA INDIVIDUALIDADE.\n', 'EU SOU AQUELE CAVALEIRO ESPECIAL, QUE UM DIA TOMBOU PELA FORÇA IRREDUTÍVEL DO MEU TRISTE PENSAMENTO.\n', 'ARREPENDIDO, ATRAVESSEI MARES, TERRA E ESPAÇO, EM BUSCA DA TUA COMPREENSÃO, E PELA MISSÃO ME CONFIASTES. SOU AQUELE CAVALEIRO, JESUS, PORÉM, QUE ORA SABE O QUE QUER.\n', 'QUERO A TI JESUS QUERIDO, COM OS PODERES DO MEU PAI CELESTIAL QUE ESTÁ NO CÉU. SÃO VIDAS COM DESTINOS IGUAIS, SÃO LAÇOS DE AMOR QUE NOS IMPULSAM PARA UM MUNDO MELHOR, A NOVA ERA!\n', 'A FELICIDADE DOS POVOS, NA CURA DESOBSESSIVA É O QUE VIVEMOS. SOU CAVALEIRO ESPECIAL, SOU JAGUAR, TRABALHANDO EM BUSCA DE MINHAS HERANÇAS TRANSCENDENTAIS, QUE FORTALECEM O MEU SOL INTERIOR, FAZENDO-ME ESTE PODER DECRESCENTE INICIÁTICO DA CURA DO PLEXO-FÍSICO. E EM TEU SANTO NOME, PARTIREI SEMPRE COM - 0 - / / EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const ninfaSolCanto = {
    title: 'CANTO DA NINFA DO CAVALEIRO ESPECIAL (NINFA SOL)',
    text: ['SALVE DEUS!\n', 'MEU MESTRE REINO CENTRAL, ESTAMOS À VOSSA MERCÊ.\n', 'OH! JESUS, CAMINHAMOS NA DIREÇÃO DA ESTRELA TESTEMUNHA QUE NOS REGE NESTE UNIVERSO. CAMINHAMOS NA FORÇA ABSOLUTA QUE VEM DE DEUS PAI TODO-PODEROSO.\n', 'SOU NINFA DO CAVALEIRO VERDE ESPECIAL.\n', 'CONFIANTE NOS PODERES DIVINOS, EMITO O MEU PRIMEIRO PASSO, PARA QUE OS PODERES DE NOSSAS HERANÇAS TRANSCENDENTAIS, NOS CHEGUEM PARA CONTINUAÇÃO DESTA JORNADA.\n', 'E COM A LICENÇA DE VOSSA MERCÊ, PARTIREI SEMPRE COM – 0 – // EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const ninfaLuaCanto = {
    title: 'CANTO DA ESCRAVA DO CAVALEIRO ESPECIAL (NINFA LUA)',
    text: ['SALVE DEUS!\n', 'MEU MESTRE REINO CENTRAL, ESTAMOS À VOSSA MERCÊ.\n', 'OH JESUS! CAMINHAMOS NA DIREÇÃO DA ESTRELA TESTEMUNHA QUE NOS REGE NESTE UNIVERSO. CAMINHAMOS NA FORÇA ABSOLUTA QUE VEM DE DEUS PAI TODO-PODEROSO.\n', 'SOU ESCRAVA DO CAVALEIRO VERDE ESPECIAL.\n', 'CONFIANTE NOS PODERES DIVINOS, EMITO O MEU PRIMEIRO PASSO, PARA QUE OS PODERES DE NOSSAS HERANÇAS TRANSCENDENTAIS, NOS CHEGUEM PARA CONTINUAÇÃO DESTA JORNADA.\n', 'E COM A LICENÇA DE VOSSA MERCÊ, PARTIREI SEMPRE COM – 0 – / / EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};