export const agulhaIsmeniaCanto = {
    title: 'CANTO DA AGULHA ISMÊNIA',
    text: ['SALVE DEUS!\n', 'OH JESUS!\n', 'ESTA É A HORA DA MINHA INDIVIDUALIDADE, TUA FILHA TE QUER FALAR.\n', 'EU SOU A MISSIONÁRIA DESTINADA A NOVA ERA, SOU ESPARTANA.\n', 'VENHO DAS CORDILHEIRAS, ATRAVESSEI A VELHA PALESTINA.\n', 'VIVI OS ENCANTOS, NO RICO VALE DOS REIS.\n', 'OH JESUS! QUE AS FORÇAS SE DESLOQUEM ATÉ A MIM. PARA QUE EU POSSA LIBERTAR O GRANDE AMOR, QUE OS DESATINOS NOS SEPARAM.\n', 'FUI ISMÊNIA.\n', 'SOU UMA RAINHA ISMÊNIA, TENHO A LANÇA LUMINOSA DA VIDA E DO AMOR, QUE ME DESTES, OH JESUS QUERIDO!\n', 'LANÇA LUMINOSA DO PODER DA NINFA ESMÊNIA.\n', 'QUERO A FORÇA, JESUS QUERIDO! NA LEI DE AUXÍLIO, PARA ILUMINAR OS MEUS FAMILIARES, OS MEUS IRMÃOS JAGUARES!\n', 'COM – 0 –, EM TI JESUS QUERIDO!\n', 'SALVE DEUS!'],
    repeat: 2
};

export const aponaraCanto = {
    title: 'CANTO DA APONARA',
    text: ['SALVE DEUS!\n', 'OH, JESUS! OH, SIMIROMBA MEU PAI! CONFIRMO AQUI: A MAGIA É UMA CIÊNCIA QUE NINGUÉM PODE ABUSAR SEM PERDÊ-LA E SEM PERDER A SI MESMO.\n', 'OS SOBERANOS SACERDOTES SÃO MUITO GRANDES PARA SE EXPOREM, POIS SABEMOS QUE A MAGIA EXPOSTA NÃO É A MAGIA DE NOSSO SENHOR JESUS CRISTO. MESMO SE UM SOBERANO, POR UMA INFELICIDADE, CHEGASSE A EXPÔ-LA, CAIRIA E SERIA UMA TOTAL REVOLUÇÃO, PORQUE ATINGIRIA MEIO MUNDO.\n', 'TAIS SÃO AS REVELAÇÕES DA ALTA CABALA E SUAS FORÇAS CONTIDAS E EXPOSTAS NOS FENÔMENOS E MISTÉRIOS ACORRENTADOS, QUE NATURALMENTE SE DESAGREGARIAM SEM DÚVIDAS, PARA A CIÊNCIA QUE APOIADA EM SEUS FALSOS PRECONCEITOS, NÃO SE ENCONTRARIA VERDADEIRAMENTE.\n', 'NO ENTANTO, UMA SÉRIE DE INDUÇÕES E JUNÇÕES RIGOROSAS DO CÉU ESQUECEM OS FATOS E VÃO EMITINDO NA MAGIA DE NOSSO SENHOR JESUS CRISTO OS SEGREDOS MAIS PERIGOSOS E TODO O SEU MISTÉRIO É O EQUILÍBRIO! É A GRANDE LEI VITAL QUE PROJETAMOS. SE PROJETAMOS COM VIOLÊNCIA SOMOS REPELIDOS POR UMA NATUREZA MELHOR QUE A NOSSA.\n', 'ESTENDE-SE MAIS LONGE! PORÉM, A FORÇA OU ENERGIA DA ALTA MAGIA NÃO SE TRATA SOMENTE DOS FLUÍDOS MAGNÉTICOS. É A LUZ ASTRAL, MOVIMENTOS ELÉTRICOS QUE SE DESANINHAM DO HIPERETÉRICO E COMO GOTAS MANIPULADAS PELA HERANÇA TRANSCENDENTAL... RAIOS, RAIOS ELÉTRICOS EXTRAÍDOS PELA ENERGIA DOS QUE MANIPULAM PELO AMOR INCONDICIONAL.\n', 'OH, SIMIROMBA MEU PAI! ESTA É A HORA DE MINHA MEDITAÇÃO E QUE ME FAZ LEMBRAR OS MEUS ENTES QUERIDOS, OS MEUS AMORES E AQUELES QUE SE DIZEM MEUS INIMIGOS.\n', 'OH, JESUS! SÓ EM TI PODEREI ME ENCONTRAR, PORQUE SÓ EM TI VIVE A LUZ ETERNA! SALVE DEUS!'],
    repeat: 1
};

export const arianaCanto = {
    title: 'CANTO DA ARIANA DA ESTRELA TESTEMUNHA',
    text: ['SALVE DEUS!\n', 'OH JESUS! ESTE É O CANTO DA MINHA INDIVIDUALIDADE. QUERO EMITIR NESTE MANTRA TODO AMOR. QUE OS ANJOS E SANTOS EMITAM SUAS PÉROLAS EM BENEFÍCIO DESTE TRABALHO.\n', 'JESUS! QUE O PODER DOS FARAÓS, DOS RAMSÉS, DE AKHENATON, DE AMON-RÁ E DO RICO VALE DOS REIS VENHAM NA FORÇA ABSOLUTA DE DEUS PAI TODO PODEROSO PARA ASSISTÊNCIA DESTE TRABALHO, QUE MEU PAI SIMIROMBA ME CONFIOU.\n', 'CAVALEIRO DA LANÇA REINO CENTRAL,\n', 'CAVALEIRO DA LANÇA VERMELHA,\n', 'CAVALEIRO DA LANÇA LILÁS,\n', 'CAVALEIRO DA LANÇA RÓSEA,\n', 'CAVALEIROS DE OXOSSE,\n', 'VAMOS ENTRAR EM SINTONIA COM A DIVINA ESTRELA DO CÉU, EM DEUS PAI TODO PODEROSO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const caycaraCanto = {
    title: 'CANTO DA CAYÇARA',
    text: ['SALVE DEUS!\n', 'OH JESUS DIVINO E AMADO MESTRE!\n', 'QUEM TE FALA SOU EU, GUIA MISSIONÁRIA CAYÇARA, QUE RECEBEU DE DEUS PAI TODO PODEROSO, A HERANÇA TRANSCENDENTAL, JUNTO A POVOS QUE SE DESTINAM NA ESPERANÇA DE UMA NOVA ERA.\n', 'SOU MISSIONÁRIA, VINDA DO MUNDO VERDE EM MISSÃO ESPECIAL, SOU ESPARTANA, SOU JAGUAR!\n', 'OH JESUS! SOMOS VIDAS COM DESTINOS IGUAIS, TRAGO A FORÇA DE SIMIROMBA MEU PAI.\n', 'OH JESUS! ESTOU A SERVIÇO DO REINO CENTRAL. NESTE ESCUDO, JESUS, TRAGO O SIMBOLISMO DA VIDA E DO AMOR, NA ESTRELA QUE CONDUZO, QUE REPRESENTA O DEUS DO SOL E O DEUS DA LUA, QUE JUNTOS FORMAM A LEI QUE NOS REGEM NESTE AMANHECER.\n', 'OH JESUS! EMITE A FORÇA, PARA QUE EU POSSA ACOMPANHAR OS PODERES DO CAVALEIRO DA LANÇA VERMELHA.\n', 'E EM TEU SANTO NOME E DE DEUS PAI TODO PODEROSO, PARTIREI SEMPRE COM – 0 – // EM TI JESUS QUERIDO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const ciganaAganaraCanto = {
    title: 'CANTO DA CIGANA AGANARA',
    text: ['SALVE DEUS!\n', 'MEUS REAIS CONTEMPORÂNEOS, SABEMOS QUE A LEI FÍSICA QUE NOS CHAMA À RAZÃO, É A MESMA QUE NOS CONDUZ A DEUS.\n', 'QUIS A VONTADE DE DEUS NOS COLOCAR DIANTE DESTE TRIBUNAL, QUE O ABNEGADO ESPÍRITO DE ARAGANA, EM SUA SIMPLICIDADE, ALCANÇOU A MAIS GRANDIOSA GRAÇA EM DEUS PAI TODO PODEROSO.\n', 'HOJE TEMOS ESTA RICA OPORTUNIDADE DE REENCONTRAR A DOR ACRISOLADA NO ÓDIO, DESSES QUE SE DIZEM NOSSOS INIMIGOS, DESSES QUE NÃO SOUBERAM SAIR, E CONTINUAM SENDO NOSSAS VÍTIMAS DO PASSADO.\n', 'ANDAMOS, SOFREMOS, SOFREMOS POR NÃO SABERMOS AMAR, E HOJE VOLTAMOS, E COMPREENDEMOS QUE SOMENTE O AMOR NOS TRAZ A LIBERTAÇÃO.\n', 'AGORA, TEMOS A HERANÇA DO CAVALEIRO VERDE, COM SUAS REDES MAGNÉTICAS, E O AMOR DE NOSSAS GUIAS MISSIONÁRIAS.\n', 'TEMOS A CERTEZA DA LIBERTAÇÃO DESSES QUE ACRISOLAMOS, E QUE A MILÊNIOS VIVEM NO ÓDIO, NA VINGANÇA E NA DESTRUIÇÃO.\n', 'TEMOS CERTEZA, QUE HOJE ELES VOLTARÃO PARA DEUS. SALVE DEUS!'],
    repeat: 2
};

export const ciganaTaganaCanto = {
    title: 'CANTO DA CIGANA TAGANA',
    text: ['OH JESUS!\n', 'NESTA BENDITA HORA, EU QUERO FALAR COM DEUS, QUERO SENTIR TODO MEU AMOR.\n', 'EU SOU UMA PEQUENA NINFA, SOU UMA TAGANA, QUE DESEJO SERVIR POR TODO UNIVERSO, NA LUZ INICIÁTICA DO SANTO EVANGELHO.\n', 'VENHO DO MUNDO VERDE, EM MISSÃO ESPECIAL DE UMA NOVA ERA.\n', 'NA ESPERANÇA DE UM MUNDO MELHOR, E NA GRANDEZA DE DEUS PAI TODO PODEROSO, AQUI ESTAREI SEMPRE COM – 0 – // EM TI JESUS QUERIDO.\n', 'SALVE DEUS!'],
    repeat: 3
};

export const dharmoOxintoCanto = {
    title: 'CANTO DA DHARMO-OXINTO',
    text: ['SALVE DEUS!\n', 'OH JESUS!\n', 'VENHO MAIS UMA VEZ, NESTA BENDITA HORA, OFERTAR O MEU CANTO E ELEVAR MINHAS VIBRAÇÕES, NA MISSÃO EM QUE PERANTE SIMIROMBA MEU PAI, ME COLOQUEI!\n', 'SOU UMA MISSIONÁRIA DHARMO-OXINTO, E AQUI ESTOU PARA EMITIR, COM TODO O MEU AMOR, A VIDA INICIÁTICA DESTE AMANHECER.\n', 'OH JESUS!\n', 'EM TUA INFINITA MISERICÓRDIA, PERMITA QUE AS FORÇAS SE ENCONTREM, E SE ENTRELACEM COM A LUZ DA RAZÃO QUE EXISTE EM CADA VIDA, FAZENDO CRESCER EM NOSSAS CONSCIÊNCIAS, A RESPONSABILIDADE DA GRANDIOSA PARTIDA, DESTA, PARA UMA NOVA ERA.\n', 'QUISERA, OH JESUS! QUE ESTAS FORÇAS BENDITAS PUDESSEM RESPLANDECER EM MIM, PARA QUE EU, EMITINDO TODO O MEU AMOR, POSSA, ONDE ESTIVER, EM MINHA JORNADA NESTA ERA, SER O REFLEXO DO BEM E DA LUZ.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const dharmoOxintoLeito = {
    title: 'CANTO DA DHARMO-OXINTO NO LEITO MAGNÉTICO E NO TURIGANO',
    text: ['SALVE DEUS! OH PODEROSO REINO CENTRAL!\n', 'MEU MESTRE, PRIMEIRO CAVALEIRO DA LANÇA REINO CENTRAL!\n', 'EU, NINFA LUA/SOL, DA FALANGE ________________, MISSIONÁRIA DHARMO-OXINTO, POVO DE ___________, NINFA AJANÃ/ADJURAÇÃO, (nome da ninfa), VENHO EM NOME DE SIMIROMBA NOSSO PAI, COLOCAR À VOSSA DISPOSIÇÃO OS PODERES QUE ME FORAM CONFIADOS.\n', 'OH JESUS! AS LINHAS SE ENTRELAÇAM PARA A HARMONIZAÇÃO DESTE TRABALHO, NA FORÇA ABSOLUTA QUE VEM DE DEUS PAI TODO MISERICORDIOSO. SÃO LUZES QUE VÊM AO NOSSO ALCANCE! SÃO MANTRAS QUE SE ASSEMELHAM EM NOSSOS CORAÇÕES, A ESTA DIVINDADE QUE NOS CERCA.\n', 'CAVALEIRO DA LANÇA VERMELHA!\n', 'CAVALEIRO DA LANÇA LILÁS!\n', 'CAVALEIRO DA LANÇA RÓSEA!\n', 'CAVALEIROS DE OXOSSE!\n', 'OS MEUS RESPEITOS, COM TERNURA!\n', 'MEU MESTRE, PRIMEIRO CAVALEIRO DA LANÇA REINO CENTRAL, VERTICAL (se for lua) / PARTO (se for sol) COM – 0 – PORQUE – X – VOS PERTENCE.\n', 'SALVE DEUS!'],
    repeat: 1
};

export const franciscanaCanto = {
    title: 'CANTO DA FRANCISCANA',
    text: ['JESUS! NESTA BENDITA HORA VENHO UNIR-ME ÀS MINHAS IRMÃS E EMITIR O MEU CANTO, O CANTO DA MISSIONÁRIA VINDA DO MUNDO VERDE.\n', 'EU SOU, JESUS, A FRANCISCANA DE ASSIS, O SIMIROMBA DE DEUS PAI TODO PODEROSO, QUE ME ENSINOU A VERDADEIRA CURA DESOBSESSIVA DOS CEGOS, DOS MUDOS E DOS INCOMPREENDIDOS.\n', 'SEMPRE JESUS, EM TEU SANTO NOME, VIVEREI SEMPRE AO BEM DOS QUE NECESSITAM DE MIM.\n', 'EM NOME DO PAI, DO FILHO E DO ESPÍRITO.\n', 'SALVE DEUS!'],
    repeat: 3
};

export const gregaCanto = {
    title: 'CANTO DA GREGA',
    text: ['OH DEUS APOLO, UNIFICADO EM CRISTO JESUS!\n', 'AQUI ME TENS, FIRME AO CAVALEIRO VERMELHO, QUE AINDA REPOUSA SOB AS NUVENS LUMINOSAS DE ATENAS, PORÉM JÁ UNIFICADO EM DEUS PAI TODO PODEROSO.\n', 'TRAGO A FORÇA DA GUIA MISSIONÁRIA ABARIANA VERDE, A GRANDE KALY, QUE VIU OS PODERES DE POLICENA, SOBRE AS ONDAS DOS GRANDES MARES.\n', 'TUDO, TUDO NOS PERTENCE NA GUARDA DESTE TRABALHO. SIMIROMBA DE DEUS! O NOSSO PAI, VEM TRAZER A BOA SORTE AOS NOSSOS IRMÃOS.\n', 'PARTO COM – O – // EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const jacanaCanto = {
    title: 'CANTO DA JAÇANÃ',
    text: ['OH! JESUS.\n', 'É A MINHA HORA JESUS.\n', 'O CANTO DA JAÇANÃ, QUE MIL VEZES TE PEÇO A PERSEVERANÇA DO HOMEM DE MINHA TRIBO.\n', 'QUE ME DESTE NA FORÇA ABSOLUTA QUE VEM DE DEUS PAI TODO PODEROSO, O PODER DO FOGO E DA ÁGUA.\n', 'ESPERAM JESUS QUERIDO, DE MIM ESTA SIMPLICIDADE.\n', 'OH! SIMIROMBA, MEU PAI,\n', 'QUE FORÇAS RESPLANDECENTES NOS DOMINEM E NOS CONDUZAM AOS GRANDES FENÔMENOS, DE QUE O MUNDO NOS ESPERA.\n', 'OH! FORÇA ABENÇOADA DE DEUS,\n', 'QUE EM NOME DO PAI, DO FILHO E DO ESPÍRITO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const madalenaCanto = {
    title: 'CANTO DA MADALENA',
    text: ['SALVE DEUS!\n', 'EU SOU O CAMINHO DA VERDADE E DA VIDA, NINGUÉM IRÁ AO PAI SENÃO POR MIM.\n', 'TU NOS DISSESTE JESUS QUERIDO, E AQUI ESTAMOS EM ESPÍRITO E VERDADE, EM BUSCA DESTE CAMINHO QUE SERÁ A NOSSA SALVAÇÃO.\n', 'DESTE-NOS EM TEUS PROFETAS ESTA JORNADA FELIZ PARA A CURA E A VIDA DESTA TRIBO, PARA QUE O NOSSO AMOR RESPLANDEÇA NO CAMINHO.\n', 'EM NOME DO PAI E DO ESPÍRITO.\n', 'SALVE DEUS!'],
    repeat: 3
};

export const magoCanto = {
    title: 'CANTO PRINCIPAL DO MAGO',
    text: ['OH! JESUS, QUEM TE FALA SOU EU, O MENOR DOS JAGUARES, TESTEMUNHA VIVA DA ESTRELA SUBLIMAÇÃO QUE ANUNCIAVA NA MANJEDOURA, A CHEGADA DO TEU JESUS MENINO.\n', 'SOU JAGUAR, SOU MAGO, QUE ORA ACENDO A CHAMA VIVA E RESPLANDECENTE DOS QUE DESCEM DO REINO CENTRAL E PASSAM POR AQUI COMO PEQUENOS PASTORES QUE, PELA ESTRELA GUIA, CHEGARÃO A JESUS MENINO!\n', 'REPRESENTO, TAMBÉM, OS TRÊS REIS MAGOS, QUANDO NAQUELA ERA DISTANTE TE OFERECERAM INCENSO, MIRRA E OURO. E EU, JESUS, PARA TE SERVIR, ACENDO A CHAMA VIVA E RESPLANDECENTE DO PODER DA INTEGRAÇÃO PARA QUE TODOS QUE VÊM DA ESTRELA CANDENTE SEJAM ABENÇOADOS PELAS SUAS ENERGIAS, NO CLARÃO DESTE SIMBOLISMO UNIVERSAL. É A CHAMA DA VIDA E DO AMOR! QUE AS FORÇAS SE DESLOQUEM! OH! JESUS, E EU POSSA MELHOR SERVIR!\n', 'SÃO CAVALEIROS VERDES, SÃO NINFAS, SÃO TERNURAS QUE PASSAM POR AQUI, ILUMINADOS PELA ENERGIA DO SEU SOL INTERIOR, CONCENTRADA PELA SUA JORNADA, VINDA DO REINO CENTRAL.\n', 'CONTINUAREI, JESUS, SEMPRE COM – 0 – // EM CRISTO JESUS. SALVE DEUS!'],
    repeat: 2
};

export const magoAcender = {
    title: 'CANTO DO MAGO (ACENDENDO A CHAMA DA VIDA)',
    text: ['SALVE DEUS!\n', 'OH! JESUS! EU, O MENOR DE TEUS SERVOS, REPRESENTO AS TRÊS FORÇAS DO ORIENTE: INCENSO, MIRRA E OURO.\n', 'SÃO PODERES, JESUS, QUE ORA BUSCO, NA CERTEZA ABSOLUTA DE TE ENCONTRAR E RECEBER A FORÇA TRANSCENDENTAL DA HERANÇA QUE DEIXEI, POR NÃO SABER AMAR! ORA SINTO O RESPLANDECER EM MIM, NA PERSEVERANÇA DE UMA NOVA ERA, NA SEGURANÇA DO MEU SOL INTERIOR! PARTIREI SEMPRE COM – 0 – // EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 3
};

export const magoApagar = {
    title: 'CANTO DO MAGO (APAGANDO A CHAMA DA VIDA)',
    text: ['OH! JESUS, A ESTRELA TESTEMUNHA, EM SEU BRILHO SINGULAR, ENTRE TODAS A MAIS RICA ESCOLHIDA POR DEUS, QUANDO NAQUELA ERA DISTANTE ANUNCIOU JESUS MENINO, ACOMPANHOU NO DESERTO OS TRÊS REIS MAGOS DE LUZ, QUE TE OFERECERAM OURO, MIRRA E INCENSO, E, TAMBÉM, O SEU AMOR! HOJE, JESUS, QUERO TAMBÉM TE AJUDAR!\n', 'SOU MAGO PEQUENINO, QUERO A LUZ DESTA ESTRELA PARA ESTA CHAMA APAGAR, SERVINDO, EM TEU SANTO NOME, À MINHA TRIBO DE MESTRE JAGUAR, QUE EM NOME DE DEUS PAI TODO PODEROSO, OFEREÇO COM // EM CRISTO JESUS. SALVE DEUS!'],
    repeat: 3
};

export const mayaCanto = {
    title: 'CANTO DA MAYA',
    text: ['OH JESUS!\n', 'ESTA É A HORA DA INDIVIDUALIDADE!\n', 'VENHO TRAZER-TE ESTE MOMENTO DE LUZ QUE TENHO EM MEU CORAÇÃO.\n', 'RESTOS DE UMA VIDA QUE ME FEZ VOLTAR POR NÃO SABER AMAR.\n', 'CONHECI A CIÊNCIA CÓSMICA, PROMOVI A VIRGEM DO SOL, SOU TAMBÉM A ALEGRIA DA LUA.\n', 'PROCURO, JESUS, ENCONTRAR O BRILHO DA JOVEM GUERREIRA: A VIRGEM DO SOL!\n', 'OH JESUS!\n', 'TUDO QUEREMOS FAZER NESTA JORNADA PARA UMA NOVA ERA.\n', 'ESTAMOS, OH JESUS, COM – 0 – / / EM TEU SANTO NOME JESUS QUERIDO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const muruaicyCanto = {
    title: 'CANTO DA MURUAICY',
    text: ['MEU DEUS TODO PODEROSO! AQUI EU VENHO PEDIR. SÃO FORÇAS SENHOR, E EU TE VENHO FALAR. HOMENS DE MINHA TRIBO, QUE NECESSITAM DE TI NO PODER DA FORÇA ABSOLUTA, A ENERGIA DO JAGUAR.\n', 'A HARMONIA ENTRE ELES JESUS! O PODER UNIVERSAL, OS CONSELHOS DOS VELHOS SÁBIOS, OS ALBERGUES NAS NOITES DE LUAR, O ANODAY E O ANODAI, AS PÉROLAS DOS SANTOS ESPÍRITOS E DOS ANJOS DE YEMANJÁ, DO TEU SIMIROMBA.\n', 'OH BOM DEUS!\n', 'OH SIMIROMBA MEU PAI!\n', 'ESTA É A HORA DA TRIBO, É A HORA DO JAGUAR, QUE EM NOME DO PAI E DO ESPÍRITO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const muruaicyPortões = {
    title: 'CANTO DA MURUAICY (ABERTURA DOS PORTÕES)',
    text: ['- ABERTURA DO PORTÃO DA UNIFICAÇÃO\n', '\n', 'SALVE DEUS! EU MISSIONÁRIA MURUAICY, NESTA BENDITA HORA VENHO EM NOME DOS GRANDES ESPÍRITOS DO REINO CENTRAL, E EM NOME DE NOSSA MÃE CLARIVIDENTE, PEDIR AO GRANDIOSO ESPÍRITO DE YEMANJÁ, PARA ABERTURA DA UNIFICAÇÃO. SALVE DEUS!\n', '\n', '- ABERTURA DO PORTÃO DA CRUZ DO CAMINHO\n', '\n', 'SALVE DEUS! EU MISSIONÁRIA MURUAICY, NESTA BENDITA HORA VENHO PEDIR AO GRANDIOSO ESPÍRITO DE YEMANJÁ, E AO POVO DE CACHOEIRA, A PERMISSÃO PARA ABERTURA DA CRUZ DO CAMINHO. SALVE DEUS!\n', '\n', '- ABERTURA DO ORÁCULO\n', '\n', 'SALVE DEUS! EU MISSIONÁRIA MURUAICY, NESTA BENDITA HORA VENHO PEDIR A DEVIDA PERMISSÃO AO GRANDIOSO SIMIROMBA DE DEUS, O NOSSO PAI SETA BRANCA, PARA ABERTURA DO ORÁCULO. SALVE DEUS!\n', '\n', '- ABERTURA DA CABALA\n', '\n', 'SALVE DEUS! EU MISSIONÁRIA MURUAICY, NESTE INSTANTE VENHO EM NOME DOS GRANDES INICIADOS, E DE NOSSA MÃE PÍTIA, PEDIR A PERMISSÃO AO REINO CENTRAL PARA A ABERTURA DA CABALA. SALVE DEUS!'],
    repeat: 1
};

export const narayamaCanto = {
    title: 'CANTO DA NARAYAMA',
    text: ['OH, JESUS!\n', 'EU OLHEI PARA O SOL, E SENTI QUE OS MEUS IRMÃOS LÁ DO ALTO ME OLHAVAM COM TERNURA E REPARAÇÃO...\n', 'OLHEI PARA O CÉU: SENTI QUE TODO O UNIVERSO ETÉRICO SE PREOCUPAVA COMIGO...\n', 'SENTI TAMBÉM, JESUS, QUE TUDO O QUE EU PEDIA, NÃO DEPENDIA DE LÁ, E SOMENTE DAQUI TODA GRANDEZA PARTIRIA...\n', 'VI ENTÃO, JESUS, QUE BUSCAMOS O QUE JÁ TEMOS AQUI, E QUE O MUNDO ILUMINA AOS QUE SABEM CONQUISTAR E NÃO AOS QUE VIVEM DAS CONQUISTAS DESCOBERTAS!...\n', 'E SENTINDO, JESUS, TODO O AMOR DESTA REVELAÇÃO, PEÇO FORÇAS PARA QUE EU NÃO VENHA A FRAQUEJAR NA CONQUISTA UNIVERSAL DESTA MISSÃO!\n', 'PARA SEMPRE... SEM FIM...\n', 'E PARTO COM – 0 – EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const niatraCanto = {
    title: 'CANTO DA NIATRA',
    text: ['SALVE DEUS!\n', 'OH BENDITA LUZ DO REINO CENTRAL!\n', 'FORÇA ABSOLUTA QUE VEM DE DEUS MISERICORDIOSO!\n', 'EMITE EM MEU CORAÇÃO, PARA QUE EU POSSA CONSERVAR A TOLERÂNCIA DE COMPREENSÃO.\n', 'QUE TODO AMOR FRATERNAL DA HERANÇA TRANSCENDENTAL, POSSA IMPREGNAR O MEU SOL INTERIOR, FAZENDO-ME SENTIR O PRAZER DESTE MUNDO, QUE AINDA VIVE O MEU PLEXO FÍSICO.\n', 'EMITE TAMBÉM, OH SIMIROMBA, MEU PAI, O MEU ANODAÊ, QUE ME DÁ ALEGRIA DE VIVER E FORTALECE OS TRÊS REINOS DE MINHA NATUREZA.\n', 'OH GRANDE ORIENTE DE OXALÁ!\n', 'FAZEI COM QUE AS FORÇAS SE MOVIMENTEM EM MEU FAVOR, E COM ELAS, EU POSSA DESLOCAR-ME PARA OUTROS MUNDOS, TAMBÉM EM FAVOR DE ALGUEM MENOS ESCLARECIDO OU QUE, NECESSITADO DA FORÇA LUZ DO JAGUAR, POSSA DISPOR DO MEU AMOR!\n', 'OH SIMIROMBA MEU PAI! ESTA É A HORA DE MINHA MEDITAÇÃO, E QUE ME FAZ LEMBRAR OS MEUS ENTES QUERIDOS, OS MEUS AMORES E AQUELES QUE SE DIZEM OS MEUS INIMIGOS.\n', 'SINTO AS FORÇAS QUE SE DESLOCAM E SE PROJETAM EM TODO O MEU SER, FAZENDO-ME FELIZ!\n', 'COM – 0 – EM TI JESUS QUERIDO!\n', 'SALVE DEUS!'],
    repeat: 1
};

export const nityamaCanto = {
    title: '1° CANTO DA NITYAMA',
    text: ['OH! JESUS! FOI A VONTADE DE DEUS, TRAZER-ME DE VOLTA NESTE MUNDO FÍSICO DE DEUS PAI TODO PODEROSO, VOLTEI APÓS ENFRENTAR MAGOS E PITONISAS E NA CHAMA ARDENTE DO LENHO INVOCO AS FORÇAS SAGRADAS DOS DEVAS, SEMPRE NA DEFESA ABSOLUTA DO HOMEM DA MINHA TRIBO, PEDINDO SEMPRE A JESUS A VOLTA DE SUAS ORIGENS E AS HERANÇAS TRANSCENDENTAIS DOS MUNDOS QUE DEIXAMOS.\n', 'OH! JESUS! FIRME NESTE PROPÓSITO PARTO COM – 0 – // EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 3
};

export const nityamaChama = {
    title: '2° CANTO DA NITYAMA',
    text: ['OH! JESUS! EU SOU A NITYAMA, DO LENHO E DAS PAIXÕES, FIZ MIL CHAMAS, SUBI E CHEGUEI ATÉ OS DEVAS, RECEBI AS SUAS BÊNÇÃOS E ROGUEI DE JOELHOS PELOS MEUS AMORES.\n', 'JESUS! AQUI ESTOU PARA TE ENCONTRAR, SOU EU QUEM CANTA ABRINDO OS CAMINHOS DO MEU MESTRE JAGUAR, ESTOU A MANIPULAR AS FORÇAS COM TERNURA, ATÉ QUE MEU MESTRE, MAGO DESTE AMANHECER, QUE JUNTOS ACENDEMOS A CHAMA DA VIDA, ILUMINANDO O CAMINHO DOS MESTRES QUE DESCEM DO REINO CENTRAL, DE SUAS JORNADAS E PASSAM POR AQUI, VINDOS CARREGADOS DE ENERGIAS.\n', 'OH! JESUS, OH! MEU PAI SETA BRANCA, OH! SIMIROMBA DE DEUS! PARTIREI SEMPRE COM – 0 – // EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const nityamaTurigano = {
    title: 'CANTO DA NITYAMA NO TURIGANO',
    text: ['OH! DEUS APOLO UNIFICADO EM CRISTO JESUS! REVISTAI AQUI O TEU POVO, QUE NA FORÇA ABSOLUTA DE SIMIROMBA NOSSO PAI, PREPARA O ESPIRITO ESPARTANO NA FIGURA DO MESTRE JAGUAR, PARA QUE SIGAM SEUS CAMINHOS MATERIAIS NA FORÇA DESTE TURIGANO, QUE SIGAM TODOS, TODOS PROTEGIDOS DE QUALQUER CORRENTE NEGATIVA E QUE SOMENTE O AMOR ENCONTRE ACESSO EM TODO NOSSO SER.\n', 'E PARA QUE NOVAS FORÇAS VENHAM A VIBRAR, PEÇO A PRESENÇA DA GUIA MISSIONÁRIA, NA FORÇA ABSOLUTA DA 1ª GUIA MISSIONÁRIA ARAGANA VERDE ISIS.\n', 'ASSIM CONFIANTE JESUS QUERIDO SIGO COM – 0 – // EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const principeMayaCanto = {
    title: 'CANTO DO PRÍNCIPE MAYA',
    text: ['OH! JESUS.\n', 'ESTA É A HORA PRECISA DE MINHA VIDA, TEU FILHO TE QUER FALAR.\n', 'EU SOU AQUELE CAVALEIRO DAS CORDILHEIRAS, QUE DESCEU PARA ENFRENTAR O MUNDO, QUE SE DESTINAVA À ESTRELA TESTEMUNHA, QUE UNIA AS TRIBOS NUM SÓ PENSAMENTO, NUMA SÓ EVOLUÇÃO.\n', 'EU SOU UM ESPÍRITO ESPARTANO!\n', 'EU VI A LUZ DA VERDADE!\n', 'PORÉM, FUI AQUELE QUE FRACASSOU!\n', 'EM VEZ DA LUZ, TRISTE PERCORRI OS CAMINHOS.\n', 'FRACASSEI POR NÃO SABER AMAR.\n', 'E NESTA BENDITA HORA, JESUS, SÓ TU PODERÁS ME DAR A PAZ.\n', 'QUERO GRITAR AO MUNDO INTEIRO, NO CALOR DESSA DOUTRINA: SALVE DEUS JESUS QUERIDO!\n', 'TENHO A FORÇA BENDITA DESTE AMANHECER, PELO PAI SETA BRANCA ESTOU AQUI.\n', 'OBEDEÇO E OBEDECEREI ÀS LEIS QUE ME REGEM, DESTE AMANHECER.\n', 'SOU MAYA E PARTO COM – 0 – EM TI CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const rochanaCanto = {
    title: 'CANTO DA ROCHANA',
    text: ['OH JESUS! ESTA É A HORA FELIZ DA MINHA VIDA, QUE ORA SINTO DESPERTAR EM MIM TODO ESTE AMOR.\n', 'GUIA-ME JESUS! SOU UMA ROCHANA, E VENHO DE TERRAS DISTANTES EM BUSCA DE TE ENCONTRAR.\n', 'OH JESUS! DAI-ME FORÇAS PARA QUE EU POSSA EMITIR O MEU CANTO SILENCIOSO, DA CURA DESOBSESSIVA DOS CEGOS, DOS MUDOS E DOS INCOMPREENDIDOS.\n', 'JESUS! É A HORA DA INDIVIDUALIDADE, E ME FAZ, JESUS, SENTIR A TUA GRANDEZA EM DEUS PAI TODO MISERICORDIOSO, QUE ME DEU ESTA RICA OPORTUNIDADE DE REPARAR MEUS ERROS COM AMOR, QUE UM DIA ERREI POR NÃO SABER AMAR.\n', 'ENSINA-ME JESUS! A DISTRIBUIR ESTA MARAVILHA A TODOS AQUELES QUE DE MIM NECESSITAREM.\n', 'DAI-ME JESUS! O PODER DE EMANAR A LUZ DESTA DOUTRINA, TRANSFORMANDO SEMPRE PARA O BEM, ATÉ CONSEGUIR, JESUS, LEVÁ-LOS A CAMINHO DE DEUS PAI TODO PODEROSO, DEIXANDO QUE AS PÉROLAS DOS ANJOS E SANTOS ESPÍRITOS, SEJAM MINHA ESPERANÇA E MINHA GUIA.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const samaritanaCanto = {
    title: 'CANTO DA SAMARITANA',
    text: ['OH JESUS! ESTE É O CANTO DA SAMARITANA QUE A DOIS MIL ANOS SUSPIRA POR TI.\n', 'JESUS! AQUI ME TENS EM MISSÃO ESPECIAL, EU E MINHAS IRMÃS,COM O MESMO ESPÍRITO DAQUELA SAMARITANA QUE UM DIA SERVIU A TI GRANDE MESTRE, NA PASSAGEM DO TEU CALVÁRIO.\n', 'HOJE ESTOU AQUI, NA MINHA INDIVIDUALIDADE, LEVANDO ÀS LEGIÕES O QUE MAIS ME FOR POSSÍVEL E O QUE TANTO PRECISAMOS RECEBER. É A LUTA PARA UMA NOVA ERA. VENHO DE MUNDOS AFINS EM BUSCA DE TE SERVIR.\n', 'JESUS! QUE AS FORÇAS SE DESLOQUEM EM MEU FAVOR. SERVINDO TEUS MESTRES, SERVIREI TAMBÉM A TI.\n', 'OH MEU JESUS! ELES VÊM DO REINO CENTRAL, CONFIANTES NAS PALAVRAS QUE NAQUELA TARDE LONGÍNQUA NOS DISSESTES: “QUEM BEBER DA ÁGUA QUE EU LHE DER, NÃO MAIS TERÁ SEDE ETERNAMENTE”\n', 'DISSESTES JESUS, E TUDO SE CLAREOU NAQUELE INSTANTE. HOJE ESTOU AQUI, COM – 0 – EM TI JESUS QUERIDO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const samaritanaTurigano = {
    title: 'CANTO DA SAMARITANA NO TURIGANO',
    text: ['OH JESUS!\n', 'VOLTO NESTA BENDITA HORA PARA AGRADECER A DEUS A FELIZ OPORTUNIDADE DE MINHAS IRMÃS, QUANDO, NAQUELA ERA DISTANTE, TE OFERECERAM A ÁGUA DE SUA ÂNFORA, TE LIBERTANDO DA SEDE.\n', 'HOJE, SERVIREI EM SEU LUGAR. QUERO SERVIR AMANDO, SERVINDO SEMPRE EM TEU SANTO NOME, PELO PÃO DE CADA DIA.\n', 'E NA FORÇA DECRESCENTE DE MINHA MISSÃO, PARTO COM – 0 – / / EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 3
};

export const tupinambaCanto = {
    title: 'CANTO DA TUPINAMBÁ',
    text: ['OH JESUS! DIVINO E AMADO MESTRE!\n', 'NESTA BENDITA HORA, VENHO EM TEU SANTO NOME, EMITIR O MEU CANTO DE MISSIONÁRIA TUPINAMBÁ.\n', 'TRAGO O DESTINO NESTA RICA OPORTUNIDADE QUE ME FOI DADA JUNTO AOS MEUS IRMÃOS, ENSINAR O CAMINHO AOS QUE, DESAMPARADOS, VÊM PROCURAR ESTA GRANDEZA ABSOLUTA DE DEUS PAI TODO PODEROSO.\n', 'DAI-NOS FORÇAS JESUS! PARA MELHOR VOS SERVIR NA CURA DESOBSESSIVA DOS CEGOS, DOS MUDOS E DOS INCOMPREENDIDOS.\n', 'GRANDEZA DE DEUS QUE O NOSSO JESUS AMADO NOS CONFIOU, NESTA JORNADA PARA O TERCEIRO MILÊNIO, QUE AS FORÇAS NOS CHEGUEM PARA QUE EU POSSA ENCAMINHAR, AJUDANDO ESTES QUE CHEGAM EM BUSCA DA CURA DE SEUS MALES FÍSICOS E ESPIRITUAIS.\n', 'EM TEU SANTO NOME JESUS, ESTAMOS AQUI, A MERCÊ DO TEU JULGAMENTO.\n', 'JESUS QUERIDO! VENHO DO MUNDO VERDE, E HOJE SOU A MISSIONÁRIA, UMA MISSIONÁRIA ESPECIAL EM TEU SANTO NOME.\n', 'EM NOME DO PAI, DO FILHO E DO ESPÍRITO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const yuricyLuaCanto = {
    title: 'CANTO DA YURICY LUA',
    text: ['SALVE DEUS!\n', 'OH JESUS!\n', 'ESTE É O MEU CANTO, O CANTO DA YURICY NA FORÇA BENDITA DO LUAR.\n', 'LUA! DIVINA FORÇA DECRESCENTE QUE IMANTRA A TERRA, EFLÚVIOS LUMINOSOS NO RAIAR DE UMA NOVA ERA.\n', 'JESUS!\n', 'VIVO A ESPERANÇA DA NOITE E DO DIA! PEÇO QUE DESLOQUEM AS FORÇAS DO CÉU EM MEU FAVOR. QUERO SENTIR O HOMEM DE MINHA TRIBO, O MESTRE JAGUAR!\n', 'SOU TAMBÉM NINFA JAGUAR. VENHO JESUS, NA MINHA INDIVIDUALIDADE, PEDIR OS MANTRAS LUMINOSOS PARA A ÚLTIMA CONCENTRAÇÃO NESTE ANO DO FECHAMENTO DE UMA ERA MILENAR.\n', 'JESUS!\n', 'LEVAREMOS ROSAS DE AMOR, ENFEITAREMOS ESTA JORNADA, NO DESEJO DE UM MUNDO MELHOR, ESTAREI SEMPRE COM – 0 – / / EM TI JESUS QUERIDO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const yuricySolCanto = {
    title: 'CANTO DA YURICY SOL',
    text: ['SALVE DEUS!\n', 'CAVALEIRO DA LANÇA REINO CENTRAL!\n', 'CAVALEIRO DA LANÇA VERMELHA!\n', 'CAVALEIRO DA LANÇA LILÁS!\n', 'CAVALEIRO DA LANÇA RÓSEA!\n', 'MEUS RESPEITOS COM TERNURA PARA ENTRARMOS EM SINTONIA.\n', 'JESUS! ESTA É A HORA PRECISA DE NOSSAS VIDAS, VENHO NESTE BENDITO MOMENTO, FORMAR NOSSO CANTO UNIVERSAL PARA MELHOR SERVIRMOS NESTA ERA.\n', 'QUISERA OH JESUS! QUE AS PÉROLAS DOS ANJOS E DOS SANTOS ESPÍRITOS SE HARMONIZASSEM NO MEU ATON, QUE AS SETE ESTRELAS DO ORIENTE, NA ESTRELA SUBLIMAÇÃO, EMITAM OS SEUS RAIOS NO CANTO DA YURICY, NO TRISTE REINO DE DELFOS, MINHA MÃE CLARIVIDENTE, RESPONDA AQUI NESTE MANTRA, OS PODERES DE AKHENATON, DE ARAKÉN, DOS RAMSÉS E DE AMON-RÁ, SEUS EFLÚVIOS A BRILHAR, NA SINTONIA DESTA FORÇA ABSOLUTA QUE VEM DE DEUS PAI TODO PODEROSO.\n', 'SALVE DEUS!'],
    repeat: 2
};

export const yuricySol1Canto = {
    title: 'CANTO DA YURICY SOL (PRIMEIRO CANTO)',
    text: ['OH JESUS!\n', 'ESTA É A HORA PRECISA DA INDIVIDUALIDADE DE NOSSAS VIDAS, DE MINHA VIDA.\n', 'OH JESUS!\n', 'É A HORA QUE DENTRO DE MIM, ASSISTO O DESPERTAR DAS FORÇAS, NA FORÇA ABSOLUTA QUE VEM DE DEUS TODO PODEROSO.\n', 'QUISERA OH PERFEIÇÃO, QUE AS PÉROLAS DOS ANJOS E DOS SANTOS ESPÍRITOS, ENCONTRASSEM ACESSO NOS HOSPITAIS, NOS PRESÍDIOS, ONDE GEMEM E CHORAM OS INCOMPREENDIDOS, NA DESARMONIA QUE HORA NÃO TE CONHECEM.\n', 'DAÍ A LUZ DA VIDA E DA MORTE, ILUMINA O VIANDANTE NA SUA OBSCURIDADE, ILUMINA OS CEGOS, TAMBÉM, NA SUA OBSCURIDÃO, ILUMINA, OH JESUS, OS CAMPOS ORVALHADOS, AS CORDILHEIRAS SILENCIOSAS ÀS MARGENS DO RIO CAUDALOSO, ONDE VIVE A CHOUPANA E O LAVRADOR, A CACHOEIRA DAS MATAS, O CABOCLO E SEUS AMORES, O SAVEIRO NO MAR DISTANTE, O MENINO E A MENINA, A JOVEM MÃE ABANDONADA, O ÓRFÃO DE PAI E MÃE VIVOS.\n', 'NOS LIBERTE SENHOR, DA CALÚNIA, DA FALSIDADE E DO DESPREZO.\n', 'MESTRES DESTA CONSAGRAÇÃO! VAMOS EMITIR TODO O NOSSO AMOR, PARA QUE EFLÚVIOS LUMINOSOS NOS ALCANCEM E NOS PROTEJAM, NA LUZ DOS NOSSOS CAMINHOS CÁRMICOS.\n', 'MEUS IRMÃOS E MEUS MESTRES, MENTALIZEMOS O QUE FORMAMOS NESTE CANTO, PARA QUE OS GRANDES INICIADOS DISTRIBUAM DE NOSSAS MENTES, PARA O FENÔMENO DESOBSESSIVO.\n', 'MUNDO ENCANTADO DOS HIMALAIAS! POVO DE DEUS! RAIO DE ARAKÉN! PODER DA VIDA E DO AMOR! DO MEU AMOR, DO NOSSO AMOR, DO AMOR INCONDICIONAL, QUE EM NOME DO PAI, DO FILHO E DO ESPÍRITO, DO SOL E DA LUA.\n', 'SALVE DEUS!'],
    repeat: 1
};

export const yuricyTurigano = {
    title: 'CANTO DA YURICY NO TURIGANO',
    text: ['OH JESUS!\n', 'NESTE INSTANTE PISO O SOLO DO TURIGANO, FAZENDO PRESENTE NO SANTUÁRIO DE DELFOS, O DEUS APOLO UNIFICADO EM DEUS PAI TODO PODEROSO.\n', 'DEUS APOLO! DELFOS! PODERES ENCANTADOS QUE ME ENVOLVERAM ATÉ AQUI, PARA ALCANÇAR A NOVA ERA.\n', 'É O PÃO NOSSO DE CADA DIA, GRANDEZA INFINITA DESTE AMANHECER!\n', 'FAZE COM QUE EU SEJA O JAGUAR MEDIANEIRO DA CONQUISTA UNIVERSAL. DAI-NOS SENHOR, O PODER DA MENTE E DO CENTRO NERVOSO QUE É A MISERICÓRDIA DE TE CONHECER EM DEUS PAI TODO PODEROSO.\n', 'PARTO COM – 0 – / / EM CRISTO JESUS.\n', 'SALVE DEUS!'],
    repeat: 2
};