import { IAdjunto, ICavaleiro, IFalange, IMedium, IMentor, ITemplo } from "src/types/types";

export const emissaoText = (medium: IMedium, mediuns: Array<IMedium>, ministros: Array<IMentor>, cavaleiros: Array<ICavaleiro>, guias: Array<IMentor>, adjuntos: Array<IAdjunto>, templos: Array<ITemplo>, falMiss: Array<IFalange>) => {
    const mestre = mediuns.find((item: IMedium) => item.medium_id === medium.mestre)
    const falMest = medium.falMest === 'Estrela Candente' && medium.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' && mestre?.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' ? 'ESTRELA CANDENTE, DO MINISTRO JANARÃ' : medium.falMest;
    const falMissNome = falMiss.find((item: IFalange) => item.falange_id === medium.falMiss)?.nome;
    const adjDevasNome = medium.adjDevas === 'Alufã' ? 'BARROS' : medium.adjDevas === 'Adejã' ? 'FRÓES' : '';
    const adjOrigemMin = ministros.find((min: IMentor) => min.id === adjuntos.find((item: IAdjunto) => item.adjunto_id === medium.adjOrigem)?.ministro)?.nome;
    const adjOrigemNome = adjuntos.find((item: IAdjunto) => item.adjunto_id === medium.adjOrigem)?.nome;
    const adjOrigemClassif = adjuntos.find((item: IAdjunto) => item.adjunto_id === medium.adjOrigem)?.classif;
    const esperanca = adjuntos.find((item: IAdjunto) => item.adjunto_id === medium.adjOrigem)?.esperanca;
    const termoFalange = medium.falMiss ? `${medium.regente? 'REGENTE ' : ''}${falMissNome} ${medium.janda? 'JANDA ' : ''}MISSIONÁRIA DO ADJUNTO ${medium.adjDevas} KOATAY 108 MESTRE ${adjDevasNome}. ` : '';
    const falMissNomeP = medium.falMiss === 2? 'Nityama' : falMiss.find((item: IFalange) => item.falange_id === medium.falMiss)?.nome;
    const falMissPrimeira = falMiss.find((item: IFalange) => item.falange_id === medium.falMiss)?.primeira;
    const falMissAdjMin = falMiss.find((item: IFalange) => item.falange_id === medium.falMiss)?.adjMin;
    const falMissAdjNome = falMiss.find((item: IFalange) => item.falange_id === medium.falMiss)?.adjNome;
    const termoPrimeira = medium.falMiss? `NA ORDEM DA 1ª ${falMissNomeP} ${falMissPrimeira}${falMissAdjMin ? `, NA REGÊNCIA DO ${falMissAdjMin} KOATAY 108 MESTRE ${falMissAdjNome}. ` : '. '}` : '';
    const classMest = medium.classMest.includes('Sol') ? 'Mestre Sol' : medium.classMest.includes('Luz') ? 'Mestre Luz' : medium.classMest.includes('Lua') ? 'Mestre Lua' : '';
    const prefixo = medium.med === 'Doutrinador' ? falMiss.find((item: IFalange) => item.falange_id === medium.falMiss)?.prefSol : medium.med === 'Apará' ? falMiss.find((item: IFalange) => item.falange_id === medium.falMiss)?.prefLua : ''
    const termoGuia = medium.guia ? `DA GUIA MISSIONÁRIA ${guias.find((item: IMentor) => item.id === medium.guia)?.nome} ${medium.cor} ${medium.falMiss ? prefixo : ''}` : `DE MINHA GUIA MISSIONÁRIA ${medium.falMiss ? prefixo : ''}`;
    const presidente = adjuntos.find((item: IAdjunto) => item.adjunto_id === templos.find((item: ITemplo) => item.templo_id === medium.templo)?.presidente)
    const termoEmMissaoLua = presidente?.adjunto_id !== medium.adjOrigem && !esperanca && mestre?.presidente !== 'Presidente' && mestre?.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? `EM MISSÃO DO ADJUNTO ${ministros.find((min: IMentor) => min.id === adjuntos.find((item: IAdjunto) => item.adjunto_id === presidente?.adjunto_id)?.ministro)?.nome} KOATAY 108 MESTRE ${presidente?.nome}. ` : '';
    const termoEscrava = mestre? `ESCRAVA DO ${mestre.trinoSar && mestre.trinoSol? `TRINO SARDYOS SOLITÁRIO ${mestre.trinoSol} ` : mestre.trinoSol? `TRINO SOLITÁRIO ${mestre.trinoSol} ` : mestre.trinoSar? 'TRINO SARDYOS ' : ''}${mestre.ministro? mestre.classif === 'Adjunto Regente Koatay 108 Taumantes Raio Rama Adjuração' ? `ADJUNTO REGENTE ${ministros.find((item: IMentor) => item.id === mestre.ministro)?.nome} KOATAY 108 TAUMANTES RAIO RAMA ADJURAÇÃO` : `ADJUNTO ${ministros.find((item: IMentor) => item.id === mestre.ministro)?.nome}${mestre.classif.replace(/Adjunto/g, '')}` : mestre.classif} MESTRE ${mestre.nomeEmissao}. ` : '';
    const termoEscravaArcanos = mestre? `ESCRAVA DO ADJUNTO ${ministros.find((item: IMentor) => item.id === mestre.ministro)?.nome} KOATAY 108 MESTRE ${mestre.nomeEmissao}, 7° RAIO ADJURAÇÃO ARCANOS RAMA 2000. ` : '';
    const termoYuricy = medium.falMiss === 8 ? 'NA FORÇA DO MINISTRO YURICY, ' : '';
    const termoOrigemLua = mestre?.presidente === 'Presidente' || mestre?.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? `NA ORDEM DO MINISTRO ${adjOrigemMin}. ` : esperanca? `NA ORDEM DO MINISTRO ${adjOrigemMin}, ${medium.falMiss ? 'NO' : 'DO'} ADJUNTO ${ministros.find((min: IMentor) => min.id === adjuntos.find((item: IAdjunto) => item.adjunto_id === presidente?.adjunto_id)?.ministro)?.nome} KOATAY 108 MESTRE ${presidente?.nome}. ` : `${medium.falMiss ? 'NO' : 'DO'} ADJUNTO ${adjOrigemMin} KOATAY 108 MESTRE ${adjOrigemNome}. `

    const afilhado = mediuns.find((item: IMedium) => item.medium_id === medium.afilhado)
    const termoMadrinha = afilhado? `MADRINHA DO ${afilhado.trinoSar && afilhado.trinoSol? `TRINO SARDYOS SOLITÁRIO ${afilhado.trinoSol} ` : afilhado.trinoSol? `TRINO SOLITÁRIO ${afilhado.trinoSol} ` : afilhado.trinoSar? 'TRINO SARDYOS ' : ''}${afilhado.ministro? afilhado.classif === 'Adjunto Regente Koatay 108 Taumantes Raio Rama Adjuração' ? `ADJUNTO REGENTE ${ministros.find((item: IMentor) => item.id === afilhado.ministro)?.nome} KOATAY 108 TAUMANTES RAIO RAMA ADJURAÇÃO` : `ADJUNTO ${ministros.find((item: IMentor) => item.id === afilhado.ministro)?.nome}${afilhado.classif.replace(/Adjunto/g, '')}` : afilhado.classif} MESTRE ${afilhado.nomeEmissao}. ` : '';
    const termoMadrinhaArcanos = afilhado? `MADRINHA DO ADJUNTO ${ministros.find((item: IMentor) => item.id === afilhado.ministro)?.nome} KOATAY 108 MESTRE ${afilhado.nomeEmissao}, 7° RAIO ADJURAÇÃO ARCANOS RAMA 2000. ` : '';
    const termoOrigemSol = afilhado?.presidente === 'Presidente' || afilhado?.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? `NA ORDEM DO MINISTRO ${adjOrigemMin}. ` : esperanca? `NA ORDEM DO MINISTRO ${adjOrigemMin}, ${medium.falMiss ? 'NO' : 'DO'} ADJUNTO ${ministros.find((min: IMentor) => min.id === adjuntos.find((item: IAdjunto) => item.adjunto_id === presidente?.adjunto_id)?.ministro)?.nome} KOATAY 108 MESTRE ${presidente?.nome}. ` : `${medium.falMiss ? 'NO' : 'DO'} ADJUNTO ${adjOrigemMin} KOATAY 108 MESTRE ${adjOrigemNome}. `
    const termoEmMissaoSol = presidente?.adjunto_id !== medium.adjOrigem && !esperanca && afilhado?.presidente !== 'Presidente' && afilhado?.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? `EM MISSÃO DO ADJUNTO ${ministros.find((min: IMentor) => min.id === adjuntos.find((item: IAdjunto) => item.adjunto_id === presidente?.adjunto_id)?.ministro)?.nome} KOATAY 108 MESTRE ${presidente?.nome}. ` : '';

    const termoJanata = medium.comando.includes('Janatã') && medium.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' ? 'COMANDANTE DO ADJUNTO JANATÃ MESTRE JOSÉ LUIZ. ' : '';
    const termoFalangeMS = medium.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' && medium.devas && medium.falMiss === 6 ? '' : medium.falMiss ? `${medium.regente? 'REGENTE ' : ''}${medium.falMiss === 6 ? `${medium.devas? 'MISSIONÁRIO' : 'MAGO MISSIONÁRIO' }` : medium.falMiss === 7 ? 'PRÍNCIPE MAYA DESTE AMANHECER' : ''}${medium.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' ? ` DO ADJUNTO ${medium.adjDevas} KOATAY 108 MESTRE ${adjDevasNome}` : ''}. ${medium.falMiss === 7 && medium.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' ? 'NA REGÊNCIA DO MINISTRO YURICY. ' : ''}`: '';
    const termoSetimo = medium.classif === '7° Raio Autorizado Taumantes Raio Rama Adjuração' ? '7° Raio, ' : medium.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' || medium.presidente === 'Presidente' ? '' : 'VINDO DO 7° RAIO, ';
    const termoClassifOrigem = medium.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' || medium.presidente === 'Presidente' ? '. ' : adjOrigemClassif === 'Arcanos' ? `, NA LINHA DO MESTRE ${adjOrigemNome}, 7º RAIO ADJURAÇÃO ARCANOS RAMA 2000. ` : `, NA LINHA DO MESTRE ${adjOrigemNome}, RAIO ADJURAÇÃO RAMA 2000. `;
    const termoClassifOrigemEsp = medium.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' || medium.presidente === 'Presidente' ? '. ' : `, NO ADJUNTO ${ministros.find((min: IMentor) => min.id === adjuntos.find((item: IAdjunto) => item.adjunto_id === presidente?.adjunto_id)?.ministro)?.nome} KOATAY 108 NA LINHA DO MESTRE ${presidente?.nome}, ${presidente?.classif === 'Arcanos' ? `7º RAIO ADJURAÇÃO ARCANOS RAMA 2000. ` : `RAIO ADJURAÇÃO RAMA 2000. `}`;
    const termoEmMissaoMS = presidente?.adjunto_id !== medium.adjOrigem && !esperanca && medium?.presidente !== 'Presidente' && medium?.classif !== 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? `EM MISSÃO DO ADJUNTO ${ministros.find((min: IMentor) => min.id === adjuntos.find((item: IAdjunto) => item.adjunto_id === presidente?.adjunto_id)?.ministro)?.nome} KOATAY 108 MESTRE ${presidente?.nome}. ` : '';
    const termoAfilhadoPrincipe = medium.falMiss === 7 ? 'AFILHADO DE KOATAY 108 MINHA MÃE CLARIVIDENTE EM CRISTO JESUS. ' : '';
    const termoClassifSol = `${medium.trinoSar && medium.trinoSol? `TRINO SARDYOS SOLITÁRIO ${medium.trinoSol} ` : medium.trinoSol? `TRINO SOLITÁRIO ${medium.trinoSol} ` : medium.trinoSar? 'TRINO SARDYOS ' : ''}${medium.ministro? medium.classif === 'Adjunto Regente Koatay 108 Taumantes Raio Rama Adjuração' ? `ADJUNTO REGENTE ${ministros.find((item: IMentor) => item.id === medium.ministro)?.nome} KOATAY 108 TAUMANTES RAIO RAMA ADJURAÇÃO` : `ADJUNTO ${ministros.find((item: IMentor) => item.id === medium.ministro)?.nome}${medium.classif.replace(/Adjunto/g, '')}` : medium.classif} MESTRE ${medium.nomeEmissao}. `;
    const herdeiroSardyos = mediuns.find((item: IMedium) => item.medium_id === medium.herdeiro)
    const termoSardyos = medium.trinoSar ? `HERDEIRO DO ADJUNTO ${ministros.find((item: IMentor) => item.id === herdeiroSardyos?.ministro)?.nome} KOATAY 108 MESTRE ${herdeiroSardyos?.nomeEmissao}${medium.filho? ', MEU PAI' : ''}. ` : '';
    const templo = templos.find((item: ITemplo) => item.templo_id === medium.templo)
    const termoPresidente = medium.presidente ? `${medium.presidente === 'Vice' ? 'VICE-PRESIDENTE' : medium.presidente} DO AMANHECER DE ${templo?.cidade}, ${templo?.estado.state}. ` : '';
    const estrelaCav = medium.trinoSar ? 'RANDAY' : medium.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' || medium.presidente === 'Presidente' ? 'RANDYÊ' : 'ANDAY';
    const termoCavaleiroSol = medium.cavaleiro ? `1° CAVALEIRO DA LANÇA ${cavaleiros.find((item: IMentor) => item.id === medium.cavaleiro)?.nome} VERDE ${estrelaCav}` : `MEU 1° CAVALEIRO DA LANÇA VERDE ${estrelaCav}`;
    const termoBarras = medium.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' ? '– 0 – X – X –' : medium.presidente === 'Presidente' ? '– 0 – X –' : '– 0 –';
    const sardyosFC = mediuns.find((item: IMedium) => item.medium_id === medium.herdeiro)?.nomeEmissao === adjuntos.find((item: IAdjunto) => item.adjunto_id === medium.adjOrigem)?.nome && mediuns.find((item: IMedium) => item.medium_id === medium.herdeiro)?.ministro === adjuntos.find((item: IAdjunto) => item.adjunto_id === medium.adjOrigem)?.ministro

    const termoClassifLua = `${medium.trinoSar? 'TRINO SARDYOS ' : ''}${medium.ministro? medium.classif === '5° Yurê Adjunto Regente Cautanenses Raio Rama Ajanã' ? `5° YURÊ ADJUNTO REGENTE ${ministros.find((item: IMentor) => item.id === medium.ministro)?.nome} CAUTANENSES RAIO RAMA AJANÃ` : `5° YURÊ ADJUNTO ${ministros.find((item: IMentor) => item.id === medium.ministro)?.nome}${medium.classif.replace(/5° Yurê Adjunto/g, '')}` : medium.classif} MESTRE ${medium.nomeEmissao}. `;
    const termoCavaleiroLua = medium.cavaleiro ? `CAVALEIRO DA LANÇA ${cavaleiros.find((item: IMentor) => item.id === medium.cavaleiro)?.nome} ${medium.cor? medium.cor : 'VERDE'}` : `MEU CAVALEIRO DA LANÇA ${medium.cor? medium.cor : 'VERDE'}`;
    const termoPadrinho = afilhado? `PADRINHO DO ${afilhado.trinoSar && afilhado.trinoSol? `TRINO SARDYOS SOLITÁRIO ${afilhado.trinoSol} ` : afilhado.trinoSol? `TRINO SOLITÁRIO ${afilhado.trinoSol} ` : afilhado.trinoSar? 'TRINO SARDYOS ' : ''}${afilhado.ministro? afilhado.classif === 'Adjunto Regente Koatay 108 Taumantes Raio Rama Adjuração' ? `ADJUNTO REGENTE ${ministros.find((item: IMentor) => item.id === afilhado.ministro)?.nome} KOATAY 108 TAUMANTES RAIO RAMA ADJURAÇÃO` : `ADJUNTO ${ministros.find((item: IMentor) => item.id === afilhado.ministro)?.nome}${afilhado.classif.replace(/Adjunto/g, '')}` : afilhado.classif} MESTRE ${afilhado.nomeEmissao}. ` : '';
    const termoPadrinhoArcanos = afilhado? `PADRINHO DO ADJUNTO ${ministros.find((item: IMentor) => item.id === afilhado.ministro)?.nome} KOATAY 108 MESTRE ${afilhado.nomeEmissao}, 7° RAIO ADJURAÇÃO ARCANOS RAMA 2000. ` : '';


    const ninfaMenor = `EU, NINFA ${medium.med === 'Doutrinador' ? 'SOL' : medium.med === 'Apará' ? 'LUA' : ''} DA FALANGE DE SUBLIMAÇÃO, ${termoFalange}, NO ADJUNTO ${adjOrigemMin} KOATAY 108 MESTRE ${adjOrigemNome}. ${termoPrimeira}EU, ${medium.nomeEmissao}, PARTO COM – 0 – // EM CRISTO JESUS.`

    const magoMenor = `EU, ${medium.dtElevacao ? `JAGUAR ${classMest}, DA FALANGE DE SUBLIMAÇÃO. ` : ''}MAGO MISSIONÁRIO DO ADJUNTO ${medium.adjDevas} KOATAY 108 MESTRE ${adjDevasNome}, NO ADJUNTO ${adjOrigemMin} KOATAY 108 MESTRE ${adjOrigemNome}. EU, ${medium.med === 'Doutrinador' && medium.dtElevacao ? '7° RAIO AUTORIZADO ' : medium.med === 'Apará' && medium.dtElevacao ? '5° YURÊ RAIO AUTORIZADO ' : ''}MESTRE ${medium.nomeEmissao}, PARTO COM – 0 – // EM CRISTO JESUS.`;

    const principeMenor = `EU, ${medium.dtElevacao ? `JAGUAR ${classMest}, DA FALANGE DE SUBLIMAÇÃO. ` : ''}PRÍNCIPE MAYA DESTE AMANHECER, DO ADJUNTO ${medium.adjDevas} KOATAY 108 MESTRE ${adjDevasNome}, NA REGÊNCIA DO MINISTRO YURICY, NO ADJUNTO ${adjOrigemMin} KOATAY 108 MESTRE ${adjOrigemNome}. AFILHADO DE KOATAY 108 MINHA MÃE CLARIVIDENTE EM CRISTO JESUS. EU, ${medium.med === 'Doutrinador' && medium.dtElevacao ? '7° RAIO AUTORIZADO MESTRE ' : medium.med === 'Apará' && medium.dtElevacao ? '5° YURÊ RAIO AUTORIZADO MESTRE ' : ''}${medium.nomeEmissao}, PARTO COM – 0 – // EM CRISTO JESUS.`;

    const ninfaLua = `EU, NINFA LUA ${medium.recepcao? 'RECEPÇÃO' : ''}${medium.devas? 'FILHA DE DEVAS' : ''}, DA FALANGE DE ${falMest}, POVO DE ${medium.povo}, ${termoFalange}${termoYuricy}${termoOrigemLua}${termoEmMissaoLua}${mestre?.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? termoEscravaArcanos : termoEscrava}${termoPrimeira}OH JESUS! ACABO DE RECEBER DE DEUS PAI TODO PODEROSO, A SINTONIA DO GRANDE E DIVINO MESTRE OLORUM, NA LINHA DESTE AMANHECER. DESEJANDO ALCANÇAR OS PODERES DO REINO CENTRAL, COLOCO JESUS! A TERNURA DE TODOS OS TEMPOS. EMITE JESUS! DEIXE QUE AS FORÇAS SE DESLOQUEM ATÉ O MEU PLEXO. EU, ${medium.nomeEmissao}, SOU UMA GUIA MISSIONÁRIA VINDA DO MUNDO VERDE EM MISSÃO ESPECIAL, VENHO NA FORÇA DECRESCENTE ${termoGuia}, TURNO ${medium.turnoLeg}, NA ESPERANÇA DE MINHA ESTRELA ${medium.estrela} DO MEU 2º VERBO, NA ORDEM DO 1º 7º, LEVANDO OS PODERES ${medium.mestre ? 'DO MESTRE' : 'DE MINHA MÃE KOATAY 108'} QUE ME FEZ ${medium.turnoTrab}, PARA FORTALECER O MEU SOL INTERIOR, NOS TRÊS REINOS DE MINHA NATUREZA, PARTIREI SEMPRE COM ${medium.mestre? '– 0 – 0 –' : '– 0 –'} // EM CRISTO JESUS.`

    const ninfaSol = `EU, NINFA SOL ${medium.recepcao? 'RECEPÇÃO' : ''}${medium.devas? 'FILHA DE DEVAS' : ''}, DA FALANGE DE ${medium.falMest}, POVO DE ${medium.povo}, ${termoFalange}${termoYuricy}${termoOrigemSol}${termoEmMissaoSol}${afilhado?.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? termoMadrinhaArcanos : termoMadrinha}${termoPrimeira}OH JESUS! ACABO DE RECEBER DE DEUS PAI TODO PODEROSO, A SINTONIA DO GRANDE E DIVINO MESTRE OBATALÁ, NA LINHA DESTE AMANHECER. DESEJANDO ALCANÇAR OS PODERES DO REINO CENTRAL, COLOCO JESUS! A TERNURA DE TODOS OS TEMPOS. EMITE JESUS! DEIXE QUE AS FORÇAS SE DESLOQUEM ATÉ O MEU PLEXO. EU, ${medium.nomeEmissao}, SOU UMA GUIA MISSIONÁRIA VINDA DO MUNDO VERDE EM MISSÃO ESPECIAL, VENHO NA FORÇA DECRESCENTE ${termoGuia}, TURNO ${medium.turnoLeg}, NA ESPERANÇA DE MINHA ESTRELA ${medium.estrela} DO MEU 3º VERBO, NA ORDEM DO 1º 7º, LEVANDO OS PODERES ${medium.mestre ? 'DO MESTRE' : 'DE MINHA MÃE KOATAY 108'} QUE ME FEZ ${medium.turnoTrab}, PARA FORTALECER O MEU SOL INTERIOR, NOS TRÊS REINOS DE MINHA NATUREZA, PARTIREI SEMPRE COM ${medium.mestre? '– 0 – 0 –' : '– 0 –'} // EM CRISTO JESUS.`

    const mestreSol = `EU, JAGUAR ${classMest} ${medium.recepcao? 'RECEPÇÃO' : ''}${medium.devas? medium.falMiss === 6 ? 'MAGO FILHO DE DEVAS' : 'FILHO DE DEVAS' : ''}, DA FALANGE DE ${falMest}, POVO DE ${medium.povo}. ${termoJanata}${termoFalangeMS}${termoSetimo}NA ORDEM DO MINISTRO ${adjOrigemMin}${esperanca? termoClassifOrigemEsp : termoClassifOrigem}${termoAfilhadoPrincipe}${termoEmMissaoMS}EU, ${termoClassifSol}${termoSardyos}${termoPresidente}COM OS PODERES DE OLORUM, NA LINHA DESTE AMANHECER. TENHO O MEU DEUS E MINISTRO OBATALÁ QUE ME REGE E ME GUARDA NO CAMINHO DESTA JORNADA. ACABO DE RECEBER DE DEUS PAI TODO PODEROSO NA MINHA LEGIÃO, O TÍTULO DE MESTRE INSTRUTOR UNIVERSAL DAS TRÊS FORÇAS LIGADAS AOS PODERES DESTE AMANHECER. SUBI AO REINO DE JUREMA E ESTOU NA CONTINUAÇÃO DESTA JORNADA PARA O TERCEIRO MILÊNIO. EMITE JESUS! DEIXE QUE AS FORÇAS SE DESLOQUEM ATÉ O MEU PLEXO. SOU UM CAVALEIRO VERDE, CAVALEIRO ESPECIAL, VENHO NA FORÇA DECRESCENTE DO ${termoCavaleiroSol} // REINO CENTRAL, TURNO ${medium.turnoLeg}, NA ESPERANÇA DE ALIMENTAR O MEU SOL INTERIOR, NA GRANDEZA QUE ME FEZ CAVALEIRO DO TURNO ${medium.turnoTrab}, PARTIREI NOS TRÊS REINOS DE MINHA NATUREZA COM – 0 –, DO MEU 3º 7º, NO 5º CICLO INICIÁTICO, SEGUIREI SEMPRE COM ${medium.ninfa? '– 0 ' : ''}${termoBarras} // EM CRISTO JESUS.`;

    const mestreSolSardyosFC = `EU, JAGUAR ${classMest} ${medium.recepcao? 'RECEPÇÃO' : ''}${medium.devas? medium.falMiss === 6 ? 'MAGO FILHO DE DEVAS' : 'FILHO DE DEVAS' : ''}, DA FALANGE DE ${falMest}, POVO DE ${medium.povo}. ${termoJanata}${termoFalangeMS}${termoAfilhadoPrincipe}${medium.falMiss || medium.comando.includes('Janatã') ? 'EU, ' : ''}${termoClassifSol}${termoSardyos}${termoPresidente}COM OS PODERES DE OLORUM, NA LINHA DESTE AMANHECER. TENHO O MEU DEUS E MINISTRO OBATALÁ QUE ME REGE E ME GUARDA NO CAMINHO DESTA JORNADA. ACABO DE RECEBER DE DEUS PAI TODO PODEROSO NA MINHA LEGIÃO, O TÍTULO DE MESTRE INSTRUTOR UNIVERSAL DAS TRÊS FORÇAS LIGADAS AOS PODERES DESTE AMANHECER. SUBI AO REINO DE JUREMA E ESTOU NA CONTINUAÇÃO DESTA JORNADA PARA O TERCEIRO MILÊNIO. EMITE JESUS! DEIXE QUE AS FORÇAS SE DESLOQUEM ATÉ O MEU PLEXO. SOU UM CAVALEIRO VERDE, CAVALEIRO ESPECIAL, VENHO NA FORÇA DECRESCENTE DO ${termoCavaleiroSol} // REINO CENTRAL, TURNO ${medium.turnoLeg}, NA ESPERANÇA DE ALIMENTAR O MEU SOL INTERIOR, NA GRANDEZA QUE ME FEZ CAVALEIRO DO TURNO ${medium.turnoTrab}, PARTIREI NOS TRÊS REINOS DE MINHA NATUREZA COM – 0 –, DO MEU 3º 7º, NO 5º CICLO INICIÁTICO, SEGUIREI SEMPRE COM ${medium.ninfa? '– 0 ' : ''}${termoBarras} // EM CRISTO JESUS.`;

    const mestreLua = `EU, JAGUAR MESTRE LUA ${medium.recepcao? 'RECEPÇÃO' : ''}${medium.devas? medium.falMiss === 6 ? 'MAGO FILHO DE DEVAS' : 'FILHO DE DEVAS' : ''}, DA FALANGE DE ${falMest}, POVO DE ${medium.povo}. ${termoFalangeMS}NA ORDEM DO MINISTRO ${adjOrigemMin}${afilhado?.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000' || afilhado?.presidente === 'Presidente' ? '. ' : esperanca ? termoClassifOrigemEsp : termoClassifOrigem}${termoAfilhadoPrincipe}${termoEmMissaoMS}${afilhado?.classif === 'Adjunto Koatay 108 Herdeiro Triada Harpásios 7° Raio Adjuração Arcanos Rama 2000'? termoPadrinhoArcanos : termoPadrinho}EU, ${termoClassifLua}${termoSardyos}COM OS PODERES DE OBATALÁ, NA LINHA DESTE AMANHECER. TENHO O MEU DEUS E MINISTRO OLORUM QUE ME REGE E ME GUARDA NO CAMINHO DESTA JORNADA. ACABO DE RECEBER DE DEUS PAI TODO PODEROSO NA MINHA LEGIÃO, O TÍTULO DE MESTRE INSTRUTOR UNIVERSAL DAS TRÊS FORÇAS LIGADAS AOS PODERES DESTE AMANHECER. SUBI AOS MUNDOS ENCANTADOS, SENTI AS FORÇAS BRILHAREM EM NOSSOS CORAÇÕES. EMITE JESUS! DEIXE QUE AS FORÇAS SE DESLOQUEM ATÉ O MEU PLEXO. SOU UM CAVALEIRO VERDE, CAVALEIRO ESPECIAL, VENHO NA FORÇA DECRESCENTE DO ${termoCavaleiroLua} // REINO CENTRAL, TURNO ${medium.turnoLeg}, NA ESPERANÇA DE ALIMENTAR O MEU SOL INTERIOR, NA GRANDEZA QUE ME FEZ CAVALEIRO DO TURNO ${medium.turnoTrab}, PARTIREI NOS TRÊS REINOS DE MINHA NATUREZA COM – 0 –, E NA FORÇA UNIVERSAL DO MEU 5º, SEGUIREI SEMPRE COM ${medium.ninfa? '– 0 – 0 –' : '– 0 –'} // EM CRISTO JESUS.`;

    if (medium.dtCenturia) {
        if (medium.sex.concat(medium.med) === 'MasculinoDoutrinador') {
            if (sardyosFC) {
                return mestreSolSardyosFC
            } else {
                return mestreSol
            }
        }
        if (medium.sex.concat(medium.med) === 'MasculinoApará') {
            if (sardyosFC) {
                return mestreLua
            } else {
                return mestreLua
            }
        }
        if (medium.sex.concat(medium.med) === 'FemininoDoutrinador') {
            return ninfaSol
        }
        if (medium.sex.concat(medium.med) === 'FemininoApará') {
            return ninfaLua
        }
    } else if (medium.falMiss === 1 || medium.falMiss === 2 || medium.falMiss === 4 || medium.falMiss === 5) {
        return ninfaMenor
    } else if (medium.falMiss === 6) {
        return magoMenor    
    } else if (medium.falMiss === 7) {
        return principeMenor
    } else {
        return ''
    }
}